name: Create issue on commit

on: [ push ]

jobs:
  create_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create issue using REST API
        run: |
          echo this is repo name ${{ github.repository }}
          echo this is username ${{ github.username }}
          #curl -L https://github.com/GnanasekarM-1/newapp.git
          curl --request POST \
          --url https://github.com/repos/${{ github.repository }} \
          --header 'authorization: Bearer ${{ secrets.TOKEN }}'
          ls -la
          git clone https://github.com/GnanasekarM-1/newapp.git
          ls -la 
          
