name: Create issue on commit

on: [ push ]

jobs:
  create_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create issue using REST API
        run: |
          echo ${{ github.repository }}
          echo ${{ github.username }}
          curl -L https://github.com/GnanasekarM-1/newapp.git
          
